update=08.05.2018 18:05:58
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=stm32
LibName31=74xgxx
LibName32=ac-dc
LibName33=actel
LibName34=allegro
LibName35=Altera
LibName36=analog_devices
LibName37=battery_management
LibName38=bbd
LibName39=bosch
LibName40=brooktre
LibName41=cmos_ieee
LibName42=dc-dc
LibName43=diode
LibName44=elec-unifil
LibName45=ESD_Protection
LibName46=ftdi
LibName47=gennum
LibName48=graphic
LibName49=hc11
LibName50=ir
LibName51=Lattice
LibName52=leds
LibName53=logo
LibName54=maxim
LibName55=mechanical
LibName56=microchip_dspic33dsc
LibName57=microchip_pic10mcu
LibName58=microchip_pic12mcu
LibName59=microchip_pic16mcu
LibName60=microchip_pic18mcu
LibName61=microchip_pic24mcu
LibName62=microchip_pic32mcu
LibName63=modules
LibName64=motor_drivers
LibName65=motors
LibName66=msp430
LibName67=nordicsemi
LibName68=nxp
LibName69=nxp_armmcu
LibName70=onsemi
LibName71=Oscillators
LibName72=Power_Management
LibName73=powerint
LibName74=pspice
LibName75=references
LibName76=relays
LibName77=rfcom
LibName78=sensors
LibName79=silabs
LibName80=stm8
LibName81=supertex
LibName82=switches
LibName83=transf
LibName84=triac_thyristor
LibName85=ttl_ieee
LibName86=video
LibName87=wiznet
LibName88=Worldsemi
LibName89=Xicor
LibName90=zetex
LibName91=Zilog
LibName92=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/stm32f103-china-ms
LibName93=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/74hct125d
LibName94=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/74hct245
LibName95=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/75176
LibName96=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/acorn_electron_expansion_connector
LibName97=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/arm-swd-header
LibName98=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-01
LibName99=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-03
LibName100=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/esp8266-esp-12e
LibName101=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/hm-11
LibName102=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/iso15
LibName103=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/lpc11u14fbd48
LibName104=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mcp1700t-3302e-tt
LibName105=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mcp73831t-2aci-ot
LibName106=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/micro_usb_socket
LibName107=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mke02z64vld2
LibName108=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/mke04z8vtg4
LibName109=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nRF24L01+
LibName110=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nrf24l01p_smd
LibName111=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/nrf51822-04
LibName112=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/pp_ws2812b
LibName113=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/recom-r1se
LibName114=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f37xxx_48pin
LibName115=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f102xx_48pin
LibName116=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f103c8t6-module-china
LibName117=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/stm32f302xx_48pin
LibName118=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/uart_pp
LibName119=C:/Users/Mathsterk/Documents/kicad/custom libraries/myelin-kicad-libraries-master/usb_plug
LibName120=C:/Users/Mathsterk/Documents/kicad/custom libraries/lib_w_logic/w_logic
LibName121=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/FQP30N06L/FQP30N06L
LibName122=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/ipn70r450p7s
LibName123=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/sw_spst_ms
LibName124=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/4000-ic
LibName125=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/7400-ic
LibName126=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/analog-ic
LibName127=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/avr-mcu
LibName128=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/bluegiga
LibName129=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/connector
LibName130=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/diode-inc-ic
LibName131=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/freescale-ic
LibName132=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/ftdi-ic
LibName133=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/led
LibName134=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/maxim-ic
LibName135=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/micrel-ic
LibName136=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/microchip-ic
LibName137=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/nxp-ic
LibName138=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/on-semi-ic
LibName139=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/regulator
LibName140=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/rohm
LibName141=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/sharp-relay
LibName142=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/sparkfun
LibName143=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/standard
LibName144=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/stmicro-mcu
LibName145=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/ti-ic
LibName146=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/transistor
LibName147=C:/Users/Mathsterk/Documents/kicad/custom libraries/kicad-lib-master/components/uln-ic
LibName148=C:/Users/Mathsterk/Documents/kicad/custom libraries/MATHSTERK/DIVERSE
LibName149=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Addressable-Specialty
LibName150=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName151=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Automotive-Relays
LibName152=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Balun
LibName153=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Barrel-Audio-Connectors
LibName154=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName155=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName156=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName157=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName158=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Coaxial-Connectors-RF
LibName159=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Current-Transducers
LibName160=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName161=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName162=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName163=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName164=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName165=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_DC-DC-Converters
LibName166=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Digital-Isolators
LibName167=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName168=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName169=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName170=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Diodes-Zener-Single
LibName171=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName172=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_D-Sub-Connectors
LibName173=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Embedded-Microcontrollers
LibName174=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Encoders
LibName175=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName176=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName177=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Fixed-Inductors
LibName178=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Fuses
LibName179=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Gas-Sensors
LibName180=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName181=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Image-Sensors-Camera
LibName182=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName183=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName184=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName185=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName186=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Controllers
LibName187=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName188=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-I-O-Expanders
LibName189=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Modules
LibName190=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName191=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName192=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Interface-Specialized
LibName193=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_LED-Indication-Discrete
LibName194=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName195=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName196=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName197=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Linear-Comparators
LibName198=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName199=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Flip-Flops
LibName200=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName201=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Multivibrators
LibName202=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Shift-Registers
LibName203=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName204=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName205=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName206=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName207=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName208=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Memory
LibName209=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName210=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Microphones
LibName211=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks
LibName212=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName213=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName214=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName215=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName216=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Navigation-Switches-Joystick
LibName217=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName218=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName219=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName220=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName221=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName222=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Logic-Output
LibName223=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName224=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName225=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Oscillators
LibName226=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName227=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Chargers
LibName228=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Management
LibName229=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName230=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName231=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Gate-Drivers
LibName232=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-LED-Drivers
LibName233=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName234=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName235=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName236=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName237=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName238=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Supervisors
LibName239=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Thermal-Management
LibName240=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName241=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Reference
LibName242=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName243=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName244=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName245=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName246=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName247=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName248=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Programmable-Oscillators
LibName249=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Pushbutton-Switches
LibName250=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName251=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Reed-Relays
LibName252=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Resistor-Networks-Arrays
LibName253=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Amplifiers
LibName254=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Antennas
LibName255=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Demodulators
LibName256=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Detectors
LibName257=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName258=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName259=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Receivers
LibName260=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Switches
LibName261=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-ICs
LibName262=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-Modules
LibName263=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_RF-Transmitters
LibName264=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName265=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName266=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName267=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Slide-Switches
LibName268=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Solid-State-Relays
LibName269=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Specialized-ICs
LibName270=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Specialized-Sensors
LibName271=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Surge-Suppression-ICs
LibName272=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Tactile-Switches
LibName273=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName274=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName275=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName276=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Thyristors-SCRs
LibName277=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Thyristors-TRIACs
LibName278=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Toggle-Switches
LibName279=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName280=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName281=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName282=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName283=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName284=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName285=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName286=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Transistors-JFETs
LibName287=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_Trimmer-Potentiometers
LibName288=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_TVS-Diodes
LibName289=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_TVS-Mixed-Technology
LibName290=C:/Users/Mathsterk/Documents/kicad/digikey-kicad-library/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName291=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Capacitor-2016
LibName292=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Connector-2016
LibName293=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Crystal Oscillator-2016
LibName294=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Diode-2016
LibName295=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Display-2016
LibName296=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Fuse-2016
LibName297=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-IC-2016
LibName298=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Inductor-2016
LibName299=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-LED-2016
LibName300=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Relay-2016
LibName301=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Resistor-2016
LibName302=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Sensor-2016
LibName303=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Switch-2016
LibName304=C:/Users/Mathsterk/Documents/kicad/SeeedOPL for Kicad-alpha-2017-01-02/SeeedOPL-Transistor-2016
[general]
version=1
